version: "3.7"

services:
  asaka-test-vue-3-app:
    build:
      context: .
      dockerfile: ./deployment/Dockerfile
    container_name: asaka-test-app
    restart: always
    ports:
      - "4173:4173"
    command: "yarn start"
    deploy:
      resources:
        limits:
          cpus: '0.80'
          memory: 8192M
        reservations:
          cpus: '0.50'
          memory: 8192M